import json

USELESS_TAGS = {
    "book",
    "books",
    "story",
    "stories",
    "fiction",
    "nonfiction",
    "picture book",
    "picture books",
    "board book",
    "board books",
    "general",
    "misc",
    "children",
    "kids",
    "children's literature",
    "toddlers",
    "interactive books",
    "toddler-friendly",
    "educational",
    "children's book",
    "children's books",
    "the very hungry caterpillar",
    "non-fiction",
    "party story",
"physical activity",
"surfing",
"skateboarding",
"volleyball",
"passion",
"observational",
"harvest",
"turkey",
"baby's first christmas",
"holiday celebration",
"entertainment",
"recipe",
"italian cuisine",
"instructional",
"animal friends",
"choirs",
"rap",
"love endures",
"seasonal change (summer to fall)",
"imagination/play (sandcastle building)",
"lyrical/poetic",
"joy of individual experiences",
"characters introduction",
"seasonal/holiday",
"first concepts",
"learning to read",
"pop-up book",
"cultural",
"instructive",
"astrophysics",
"kids science",
"reading comprehension",
"cognitive development",
"board books for newborn babies",
"contrasting situations",
"daytime vs. nighttime",
"passing of time",
"newborn babies",
"sea animals",
"ocean creatures",
"design",
"visual perception",
"seek-and-find",
"exploratory book",
"nocturnal animals",
"representation",
"pronouns",
"baby's lullaby",
"traditional",
"brown culture",
"inspiring",
"touch-and-feel books",
"individual experiences",
"developmental",
"apple picking",
"sorting",
"classifying",
"hands-on",
"self-dressing",
"owl and bird series",
"soccer",
"food (paninis, gelato)",
"children's fiction",
"slice-of-life",
"celebration of life",
"simple pleasures",
"walks/travel",
"jobs",
"diversity and inclusion",
"reading readiness",
"bike rides",
"park activities",
"eating",
"arts and crafts",
"coping with emotions",
"brazilian culture",
"local",
"rio de janeiro",
"s o paulo",
"brasilia",
"sugarloaf mountain",
"parque ibirapuera",
"praia do futuro",
"iguazu falls",
"mini mundo",
"amazon rainforest",
"small town life",
"brazil",
"capoeira",
"first books for babies",
"peek-a-boo reveal",
"humourous",
"proportion",
"storytelling math",
"lunar new year",
"chinese zodiac",
"toddler introduction",
"basic concepts",
"sounds of animals",
"growing",
"dragons",
"tacos",
"lively",
"alphabetical learning",
"holiday countdown",
"seasonal prep",
"generosity",
"giving",
"hiking",
"poetry/storytelling",
"nursery rhyme variation",
"celebrating disability and inclusivity",
"trick-or-treating",
"wheelchairs",
"volcano",
"jurassic era",
"listening",
"simple vocabulary",
"dialogue",
"compromise",
"loving parents",
"snack time",
"full-color board book",
"party planning",
"mesozoic era",
"assurance",
"communication",
"ocean animals",
"plants",
"features",
"agriculture",
"school communities",
"collective responsibility",
"haikus",
"flavors",
"textures",
"sensory experience",
"environmental stewardship",
"positive space",
"negative space",
"art education",
"seek and find books",
"gift",
"expecting parents",
"visual skills",
"newborn development",
"contrast",
"comparative concepts",
"word book",
"word recognition",
"lighthearted story",
"meadows",
"concern",
"interactive stories",
"gentle humor",
"early concept alphabet book",
"regional diversity",
"alphabet/numbers book",
"toddler stories",
"heart-warming",
"black american history",
"emotional well-being",
"trailblazers",
"african american history",
"family discussions",
"city",
"morning",
"sights",
"serene",
"descriptive",
"bilingualism",
"photographic board book",
"hunting",
"easter egg hunt",
"school day",
"preschooler",
"novelty book",
"naptime",
"our world series",
"toddler literature",
"birthday presents",
"unconditional support",
"read-aloud story",
"game-like",
"celebrating diversity",
"affirmative",
"animal friendship",
"playful artwork",
"animal adventure",
"daddies",
"argentina",
"sights and sounds",
"argentinean life",
"first board book",
"first book",
"safety",
"barn",
"snowstorm",
"rainbow",
"colorful",
"fearlessness",
"separation anxiety",
"poetic ode",
"milestones",
"sephardic culture",
"memoir",
"baking",
"deserts",
"spanish language",
"universe",
"development",
"first concepts book",
"self-control",
"life lessons",
"nervousness",
"children's adventures",
"nursery rhyme-inspired",
"sleep hygiene",
"moominvalley",
"acknowledging emotions",
"sisterhood",
"poise",
"canadian classic",
"anne of green gables",
"biographical tribute",
"forest",
"loneliness",
"introduction to shapes",
"recycling",
"children's",
"prehistoric world",
"rescue story",
"baby t. rex",
"preschool age",
"lullabies",
"sleep time",
"calm",
"welcome",
"first day",
"emergency services",
"animals (elephant)",
"fear/scared",
"conceptual story",
"animal life",
"emotional learning",
"over enthusiasm",
"mistakes",
"feeling upset",
"reconciliation",
"preschooler books",
"upset",
"discussional tool",
"maritime",
"boating",
"bay",
"tutus",
"kissing",
"underwater adventures",
"outdoor",
"tracking",
"learning/concepts",
"puddles",
"holiday/celebration",
"tab-interactive",
"counting/activity",
"magical transformation",
"developmental growth",
"feeling sad",
"wild",
"reading games",
"picky eaters",
"hunger",
"desire",
"adoption/love",
"best things about family",
"peekaboo",
"gift book",
"triumph",
"transport",
"rhyming picture book",
"toy workshop",
"north pole",
"reindeer",
"kitchen",
"snow boots",
"painting",
"crafts",
"pop-up books",
"magic",
"family traditions",
"non-fiction/informative",
"heroics",
"superhero",
"exhaustion",
"introduction to nature",
"zoology",
"jewish traditions",
"sibling relationships",
"coziness",
"emotional literacy",
"early childhood",
"boredom",
"disgust",
"sequential",
"simple storyline",
"sound-effect stories",
"driving",
"automotive",
"bedtime book",
"fiesta",
"bilingual",
"toddler-friendly",
"construction trucks",
"discovery",
"perception skills",
"kids' books",
"cat stories",
"delightful counting book",
"cherishement",
"giggly",
"black and brown joy",
"babies and families",
"loveable",
"inter generational",
"multigenerational story",
"tab-based book",
"toddler subject",
"giggle-worthy",
"companion book",
"new day",
"exuberance",
"ghouls",
"family love",
"award-winning author",
"mermaids",
"sea creatures",
"based on song/video",
"wanting attention",
"being a child",
"demanding behavior",
"symbolism",
"japan",
"cultural differences",
"guessing games",
"interactive elements",
"lobsters",
"peaceful",
"maple trees",
"evergreens",
"redwood trees",
"hiking trails",
"fall foliage",
"snowy forests",
"pine cones",
"nocturnal return",
"multigenerational",
"village life",
"everyday activities",
"nighttime adventures",
"busy",
"rooms",
"child's daily routine",
"pirates",
"music and movement",
"twist on a classic",
"parent-child bond",
"climbing",
"seaside adventure",
"mothers",
"landmarks",
"mexican culture",
"local foods",
"yoga",
"fitness",
"emergent readers",
"recipes",
"pig",
"japanese culture",
"diversity and representation",
"counting down",
"seasonal activities",
"toddlers learning",
"gender expression",
"non-conformity",
"self-expression",
"new addition",
"pet",
"meditation",
"sky",
"daytime",
"hope",
"habits",
"eastern deciduous forests",
"belief systems",
"ceremonies",
"identity-affirmation",
"seeds",
"flowers",
"djing",
"hospital visit",
"children's ward",
"animals (spot)",
"kids' activities",
"step-by-step instructions",
"māori culture",
"marine biology",
"dolphins",
"bottlenose dolphins",
"striped dolphins",
"spinner dolphins",
"pink dolphins",
"feeding habits",
"first-concept book",
"positive personality traits",
"zodiac signs",
"introduction to zodiac signs",
"african american author",
"celebration of family roots",
"search",
"vocabulary",
"relaxed",
"bigfeelings",
"grumpy",
"clothing",
"music education",
"instrument families",
"brass instruments",
"wind instruments",
"interactive novelty",
"mischievous",
"modern parenting",
"support",
"stigma",
"original",
"street market",
"dog",
"life-cycles",
"childrens-literature",
"life-cycle-story",
"personal space",
"social distance",
"things that go",
"neighborhood",
"corduroy",
"tour",
"ice age",
"early human culture",
"wooly mammoths",
"cavemen",
"mastodon",
"short-faced bear",
"saber-toothed cat",
"ground sloth",
"giant beaver",
"dire wolf",
"dodo bird",
"plowing fields",
"raising a barn",
"step-by-step guide",
"truck books",
"snacking",
"routine",
"bathtime",
"guide",
"mog",
"abc book",
"colour",
"sharks",
"classic cars",
"luxury brands",
"alphabetical order",
"automobiles",
"angry",
"musical instruments",
"world music",
"pacific west coast",
"rainforest",
"illustrated alphabet",
"prestige",
"school life",
"leadership",
"proud",
"baby's day routine",
"first experiences",
"rhyming texts",
"hair styles",
"spring break",
"summer vacation",
"going on vacation",
"beach trip",
"size comparison",
"animal-themed books",
"self-regulation",
"emotional-intelligence",
"child-psychology",
"infant-development",
"co-regulation",
"big-emotions",
"board-book",
"napping",
"places",
"history",
"european culture",
"self discovery",
"love story",
"hopeful",
"intersectionality",
"hand-eye coordination",
"arctic animals",
"rhyming poem",
"machines",
"berenstain bears",
"deer",
"mouse",
"finger puppets",
"interactive storybook",
"self-discovery",
"novel",
"hygiene",
"brushing teeth",
"dental health",
"possibility",
"part guessing game",
"visual narrative",
"t. rex",
"cretaceous period",
"fossils",
"scientists",
"hunting techniques",
"prehistoric environment",
"faith",
"religious",
"metaphor",
"healthy lifestyle",
"goodnight routine",
"zoo animals",
"self-reliance",
"cheekiness",
"children's storybook",
"indian festival of colors",
"holi",
"spring season",
"festivals",
"forest critters",
"quirkiness",
"freshness",
"first-person narrative",
"black-and-white images",
"life cycle",
"acorns",
"emerging readers",
"readiness for bed",
"very hungry caterpillar",
"hands-on learning",
"self-directed",
"behavioral management",
"richard scarry's busytown",
"100 essential first words",
"artwork",
"casebound",
"horticulture",
"flower gardens",
"vegetable gardens",
"planting",
"harvesting",
"animal movements",
"animal encounters",
"focus",
"stress relief",
"imitative",
"close-up photography",
"baby emotions",
"hilarious faces",
"introduction to books",
"picture-book phenomenon",
"baby and toddler books",
"global awareness",
"vampire bat",
"hippopotamus",
"great white shark",
"bush viper",
"wolf",
"question-and-answer format",
"hypothesis learning",
"delightfully",
"repeated rhyming sounds",
"rhyme scheme",
"comedy",
"growth mindset",
"lunch",
"meals",
"lionel's adventures",
"educational storybook",
"arctic",
"early learning concepts",
"snacks",
"outdoors",
"fishing",
"kayaking",
"float tubing",
"whitewater rafting",
"paddleboarding",
"riverboats",
"picnics",
"fine motor skills",
"search and find",
"serenity",
"make-believe",
"fall",
"imaginative play",
"child's daily life",
"mealtime",
"playtime",
"mealtimes for toddlers",
"play activities for toddlers",
"cheerfulness",
"illustrated children's book",
"daily routine",
"planet earth",
"goodnight",
"sweet dreams",
"road safety",
"lovable",
"participation",
"habitats",
"native animals",
"prairie provinces",
"manitoba",
"saskatchewan",
"alberta",
"letter recognition",
"curious",
"deception",
"interaction",
"animal kingdom",
"high-contrast",
"child psychology",
"jewish sabbath",
"sabbath dinner",
"shabbat candles",
"challah bread",
"red wine",
"giant pandas",
"bamboo",
"admiration",
"animal welfare",
"love of nature",
"african american boys",
"baby's first book",
"early introduction to ocean animals",
"sea monsters",
"marine reptiles",
"prehistoric creatures",
"local legends",
"oceanic wildlife",
"perspective",
"observational narrative",
"quality time",
"manners",
"teaching stories",
"mother-child bond",
"adoration",
"chores",
"making decisions",
"diligence",
"gross motor skills",
"social play",
"emotion regulation",
"overwhelm",
"relatable",
"cuddly toy",
"favorite bear",
"padded board book",
"problem solving",
"kite flying",
"vocabulary development",
"teaching",
"puzzle",
"color",
"beavers",
"simple shapes",
"prehistoric life",
"healthy diet",
"national park",
"guidebook",
"kid-friendly story",
"cultural tradition",
"jewish new year",
"australian outback",
"kangaroo family",
"cartoon-y",
"newborns",
"israel",
"sports",
"hockey",
"sports book",
"first hockey game",
"spacecraft",
"robotics",
"humility",
"beginner reader",
"alphabet/board book",
"surprising",
"bedtime routines",
"familial",
"rhyming books",
"friendliness",
"selflessness",
"giving back",
"daddy/daughter relationship",
"satisfaction",
"visual play",
"self-esteem",
"expectant parents",
"joyfulness",
"indigenous cultures",
"northwest coast",
"mousewoman legend",
"oral and visual practices",
"spirit world",
"childhood empowerment",
"folkloric/mythological",
"screen-free",
"tactile joy",
"sweet treats",
"onomatopoeic",
"good values",
"character development",
"moral lessons",
"heartbeat",
"global unity",
"dump trucks",
"cement trucks",
"monster trucks",
"uplifting",
"vibrant",
"feel-good",
"baby shower gift",
"bedtime read",
"airports",
"healthful eating",
"oakley the squirrel: the search for z",
"alphabet learning",
"earth",
"coral reef",
"animal habitats",
"lost and found",
"places around my neighborhood",
"bedtime stories",
"interactive die cuts",
"pizza",
"nap time",
"drumming",
"fatherhood",
"interactive fiction",
"natural world",
"alphabet primer",
"national parks",
"emotions (e.g. worry)",
"anxiety (or worry)",
"emergency",
"rescue",
"fire trucks",
"police",
"helicopters",
"ships",
"moonlight adventure",
"classics",
"construction site",
"surrogacy",
"adoption",
"expecting families",
"maisy series",
"concept art",
"elmo",
"puppies",
"photo story",
"fathers and sons/daughters",
"short story collection",
"comparative adjectives",
"music/singing",
"quality time with baby",
"dental hygiene",
"swimming",
"italian villanelle",
"richard scarry busytown",
"infants and toddlers",
"verb introduction",
"feeling hungry",
"story elements: setting, plot and character development",
"little monster series",
"eco-friendly",
"bedtime reading",
"mistakes as opportunities for growth",
"emotional regulation",
"guidance for parents and caregivers",
"comparison",
"big bear",
"little bear",
"boots",
"teacups",
"chairs",
"beds",
"comparative",
"siblings",
"cultural diversity",
"weather systems",
"worldwide weather",
"celebration of uniqueness",
"family values",
"enthusiasm",
"limit setting",
"unplugging",
"technology",
"behavioral guidance",
"instructional book",
"nursery",
"spot",
"interactive fun",
"interconnectedness",
"community garden",
"dogs",
"mother's day",
"festivities",
"ramadan",
"rhyme/verse",
"early numeracy",
"prehistoric animals",
"animal biology",
"coming-of-age",
"tadpole",
"frog",
"longing",
"song",
"aircraft",
"stationery design",
"giggles",
"dance",
"healthy digital habits",
"digital devices",
"photo-based",
"question-and-answer",
"timeless",
"nostalgic",
"quirky",
"fresh",
"comparative logic",
"first person narrative",
"endearing",
"day in the life",
"comparative narrative",
"body awareness",
"movement primer",
"physical development",
"guessing_game",
"sound_effects",
"board_book",
"global phenomenon",
"competition",
"animal stories",
"tactile",
"lemurs",
"story_time",
"interactive_board_book",
"infant care",
"simple story",
"mi'kmaw culture",
"indigenous art",
"baby board books",
"native american studies",
"art-based storytelling",
"matzah",
"spooky",
"jewish family",
"baby arrival",
"childhood education",
"baby's first story time",
"wildlife adventure",
"nativity scene",
"mood regulation",
"parenting tips",
"anger/frustration",
"santa claus",
"toileting",
"childhood milestones",
"merriment",
"humorous tale",
"childrens literature",
"wedding",
"marriage",
"thrilled",
"black history",
"exceptional men",
"true stories",
"historical",
"father's day gift",
"grandparent's day gift",
"birthday gift",
"special",
"classic",
"beloved",
"himalayas",
"yeti",
"snowshoes",
"mountain climbing",
"veganism",
"abc",
"hospital",
"healthcare heroes",
"doctors",
"nurses",
"patients",
"medical equipment (x-ray machine, mri, thermometer, stethoscope)",
"hospital staff (physical therapists, emts)",
"hospitals (maternity ward, emergency room, hospital gift shop)",
"wombats",
"lgbtq",
"intersectional feminism",
"sexuality",
"gender",
"celebrating all genders",
"identity affirmation",
"everyday topics",
"sexism",
"homophobia",
"transphobia",
"ableism",
"grandparents-grandchildren relationship",
"grandma and grandchild activities",
"australian bush",
"sleep and dreams",
"city life",
"holiday celebrations",
"mawlid al-nabi",
"counting pattern",
"visual stimulation",
"early childhood development",
"maria montessori theory",
"construction site adventure",
"action-packed",
"excited",
"sheep",
"identity crisis",
"embarrassment",
"hugs",
"sociable story",
"capital cities",
"provinces and territories",
"wildlife habitats",
"native species",
"iconic landmarks",
"lyrical board book",
"early concept book",
"grandparent-grandchild relationship",
"festival of lights",
"fish",
"lgbtq+",
"language awareness",
"kangaroos",
"trains",
"early concepts",
"nickelodeon's paw patrol",
"toddler fiction",
"paw patrol",
"narwhals",
"overcoming challenges",
"contentment",
"first concept book",
"birth",
"sydney harbour",
"great ocean road",
"australia zoo",
"mindil beach",
"great barrier reef",
"adelaide oval",
"uluru",
"kings park",
"salamanca market",
"outback",
"overcoming fear",
"haircut",
"barbershop",
"toddler milestones",
"improvement",
"home improvement",
"diy",
"repairing",
"polar lands",
"interactive guessing game",
"plant growth",
"everyday math",
"brother",
"wordless board book",
"books for young children",
"illustration",
"working mom",
"missing",
"children's entertainment",
"developmental play",
"daycare",
"comfortable",
"brave",
"household pets",
"super cute",
"antiracism",
"society",
"kittens",
"cuddliness",
"self-respect",
"momhood",
"family relationships",
"affirming",
"bath toys",
"creatures",
"animals that go vroom",
"babies",
"non-fiction",
"fun",
"joy",
"learning",
"happiness",
"interactive",
"excitement",
"warmth",
"joyful",
"children's story",
"toddler",
"humorous",
"education",
"humor",
"childhood",
"play",
"curiosity"
}

def clean_useless_tags(tags):
    if not tags:
        return []

    cleaned = set()

    for tag in tags:
        if not tag:
            continue

        t = tag.strip().lower()

        # remove useless exact matches
        if t in USELESS_TAGS:
            continue

        # remove very low-quality tags
        if len(t) <= 2:
            continue

        cleaned.add(t)

    return list(cleaned)
# ---------------------------
# TAG GENERATION LOGIC
# ---------------------------
def generate_tags(book):
    tags = set()

    title = (book.get("title") or "").lower()
    genres = book.get("genres") or []

    if isinstance(genres, str):
        genres = [genres]

    genres = [g.lower() for g in genres]

    # --- THEME TAGS ---
    if any(word in title for word in ["dog", "cat", "animal", "bear", "duck"]):
        tags.add("animal")

    if any(word in title for word in ["truck", "car", "bus", "train"]):
        tags.add("vehicle")

    if any(word in title for word in ["bedtime", "sleep", "goodnight", "night"]):
        tags.add("bedtime")

    if any(word in title for word in ["mom", "dad", "family", "love"]):
        tags.add("family")

    if any(word in title for word in ["food", "eat", "apple", "cake"]):
        tags.add("food")

    # --- HOLIDAY TAGS ---
    if any("easter" in g for g in genres):
        tags.add("holiday")

    if any("christmas" in g for g in genres):
        tags.add("holiday")

    # --- LEARNING TAGS ---
    if any(word in title for word in ["count", "numbers", "1 2 3"]):
        tags.add("counting")

    if any(word in title for word in ["abc", "alphabet"]):
        tags.add("alphabet")

    if any(word in title for word in ["color", "colour"]):
        tags.add("colors")

    if any(word in title for word in ["shape"]):
        tags.add("shapes")

    # --- INTERACTION TAGS ---
    if any("touch" in g for g in genres):
        tags.add("touch_and_feel")

    if any("flap" in g for g in genres):
        tags.add("lift_the_flap")

    if any(word in title for word in ["press", "sound"]):
        tags.add("interactive")

    # --- FALLBACK ---
    if not tags:
        tags.add("general")
    cleaned_tags = clean_useless_tags(tags)
    return list(cleaned_tags)


# ---------------------------
# MAIN CLEANING FUNCTION
# ---------------------------
def clean_jsonl(input_file, output_file):
    seen_ids = set()

    kept = 0
    removed_duplicates = 0
    removed_adult = 0
    removed_no_tags = 0

    with open(input_file, 'r', encoding='utf-8') as infile, \
         open(output_file, 'w', encoding='utf-8') as outfile:

        for line in infile:
            if not line.strip():
                continue

            try:
                data = json.loads(line)
            except json.JSONDecodeError:
                continue

            # ---------------------------
            # REMOVE ADULT
            # ---------------------------
            audiences = data.get("audiences", "")
            if isinstance(audiences, list):
                audiences_str = " ".join(audiences)
            else:
                audiences_str = str(audiences)

            if "ADULT" in audiences_str.upper():
                removed_adult += 1
                continue

            # ---------------------------
            # REMOVE DUPLICATES
            # ---------------------------
            book_id = data.get("id")
            if not book_id:
                continue

            if book_id in seen_ids:
                removed_duplicates += 1
                continue

            seen_ids.add(book_id)

            # ---------------------------
            # GENERATE TAGS
            # ---------------------------
            
            tags = clean_useless_tags(data.get("tags", []))

            # if not tags:
            #     removed_no_tags += 1
            #     continue

            data["tags"] = tags
            # Optional: remove raw genres
            # data.pop("genres", None)

            # ---------------------------
            # WRITE OUTPUT
            # ---------------------------
            outfile.write(json.dumps(data, ensure_ascii=False) + "\n")
            kept += 1

    # ---------------------------
    # SUMMARY
    # ---------------------------
    print("Done!")
    print(f"Kept: {kept}")
    print(f"Removed (duplicates): {removed_duplicates}")
    print(f"Removed (adult): {removed_adult}")
    print(f"Removed (no tags): {removed_no_tags}")


# ---------------------------
# ENTRY POINT
# ---------------------------
if __name__ == "__main__":
    input_path = "all_cleaned.jsonl"
    output_path = "all_cleaned2.jsonl"

    clean_jsonl(input_path, output_path)